# Generated by Django 6.0.7 on 2026-08-02 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenador_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socio',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservaclase',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app_gimnasio.socio'),
        ),
    ]
