# Generated by Django 6.0.7 on 2026-08-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gimnasio', '0002_entrenador_user_socio_user_alter_reservaclase_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='capacidad_por_hora',
            field=models.IntegerField(default=1, help_text='Cantidad máxima de alumnos que puede entrenar por hora'),
        ),
    ]
